### ISSUE TITLE
Backup initialization error

### ISSUE THREAD

**Issue by makorne** [hkbakke/rsync-backup#2]
./backup.py -a
[root] [ERROR] Backup initialization error
Traceback (most recent call last):
  File "./backup.py", line 23, in run_backup
    with rsyncbackup.RsyncBackup(config_name, test) as backup:
  File "/home/ma/rsync-backup/rsync-backup/rsyncbackup.py", line 220, in __init__
    fallback=self.global_config.getint('retention', 'snapshot')),
  File "/usr/lib/python3.5/configparser.py", line 816, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '1    # count'

**Comment by hkbakke** [comment]
Hi, try removing the comments behind the numbers of each retention line in rsync-backup.conf. I don't think that is actually allowed in the configparser ini format.

**Comment by makorne** [comment]
Hi. thank you for prompt answer!
Working under root only?
`[root] [ERROR] Backup initialization error
Traceback (most recent call last):
  File "./backup.py", line 23, in run_backup
    with rsyncbackup.RsyncBackup(config_name, test) as backup:
  File "/home/ma/rsync-backup/rsync-backup/rsyncbackup.py", line 240, in __init__
    self._is_running()
  File "/home/ma/rsync-backup/rsync-backup/rsyncbackup.py", line 769, in _is_running
    self._create_dir(os.path.dirname(self.pidfile))
  File "/home/ma/rsync-backup/rsync-backup/rsyncbackup.py", line 269, in _create_dir
    os.makedirs(directory)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/run/backup'
`

**Comment by hkbakke** [comment]
Yes. running as root is required on the host you are running rsync-backup on so rsync can enforce any combination of owner, group, permissions and ACL stuff in the backups as required. If there is another way I would be happy to implent it. I does not need root access on your backup sources though, but normally you would access those as root via keys also, to enable backup of all the files on server, regardless of permissions.

**Comment by makorne** [comment]
Many users don't need  permissions changes, just backup large folders in user's own space.

**Comment by makorne** [comment]
How to set a non 22 ssh port?

**Comment by hkbakke** [comment]
I just realized that the ssh configuration was not really flexible, so I pushed 3186797c4100cf8557384389861023fce4528c91 to master for you. You can now either `ssh_options = -p xxx` in ssh_options or the shortcut `ssh_port = xxx` in your configuration.

**Comment by makorne** [comment]
Thank you for commit! It's working.

I try to copy a folder from my pc to server

source_dir /home/ma/imgs/
rules one string:  + /home/ma/imgs/***

backup_root = /home/srv/imgs/
label  XXX.XXX.XXX.XXX

Generated string
```
root@XXX.XXX.XXX.XXX:/home/ma/imgs/ /home/srv/imgs/XXX.XXX.XXX.XXX/backups/incomplete_2017-12-21-050725/backup

[rsyncbackup.backup] [INFO] rsync: change_dir "/home/ma/imgs" failed: No such file or directory 
```
Looks like it searches for /home/ma/imgs on the server and tried to copy FROM SERVER to my pc.
How to copy from my pc to server?

**Comment by hkbakke** [comment]
I think you perhaps have misunderstood the purpose of rsync-backup. It is not a generic wrapper for rsync. It is made for a specific purpose, and that is to be a centrally managed backup server that does backups in a coordinated way of all your other servers.

It is not created to be used for all generic rsync purposes.

**Comment by makorne** [comment]
That's a shame.
Rsync takes too long to check and copy a large folder with primary unchanged files, I think your solution can speed this up.

**Comment by makorne** [comment]
For a few reasons I need $ in backup_root, like
backup_root /home/$srv/imgs

Any solution to avoid
`configparser.InterpolationSyntaxError: '$' must be followed by '$' or '{', found: "$srv/imgs/`
rsync  can do it with quotes like '/home/$srv/imgs'

**Comment by hkbakke** [comment]
Just do as it says, add a `$` after your existing `$` to escape it.

So use `/home/$$srv/imgs` in the configuration file.
The error is caused by the functionality in pythons configparser library that allows you to reference other configuration parameters as variables in your configuration using the $ syntax.
