### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by makorne** [hkbakke/rsync-backup#3]
Hi
I try to backup all imgs from a directory on remote server to a directory on current host.

source_dir /srv/imgs/
rules one string: + /srv/imgs/***

backup_root = /host/imgs/

But /host/imgs/ is empty, 
and all the data is in /host/imgs/XXX.XXX.XXX.XXX/backups/daily2018.../backup/imgs/

How do I configure this for to /host/imgs/?

**Comment by hkbakke** [comment]
Hi

rsync-backup is made for the purpose of being a backup server, not to be a generic rsync wrapper for copying data around. That means versioning and checksumming always, which again means that it has to have some datastructure on disk to be able to separate different backups, checksums etc. So the short answer is 'no', you can't put the backup data directly on the backup_root.

Your usecase seems to be a simple rsync command only however, so you don't need rsync-backup or a wrapper at all if you only want a non-versioned copy of your data from /srv/imgs to /host/imgs. Just run something like ```rsync -aviAXH --delete user@remote_host:/srv/imgs /host/imgs``` directly.
